Revert change to Irony mode to patch a now fixed bug in Clang that has not existed since about version 9
Sarcasm/irony-mode pull request #569
Opened 2020-10-15 21:09 UTC by 3246251196

I finally have got around to removing the fix introduced to irony to display non-accessibles. Recall that before version 9 of LLVM/Clang (or around that time) **protected** members/methods were not showing in derived classes in completions due to a bug in LLVM/Clang.

2020-10-15 21:12 UTC, 3246251196 commented
See #369

2020-10-16 07:25 UTC, Sarcasm requested changes
Thank you for following up on this bug.

2020-10-16 07:25 UTC, Sarcasm commented on irony-completion.el
> -(defun irony-completion-availability (candidate)
This has been removed, but it's still used by `irony-completion--filter-candidates` below.

2020-10-16 07:25 UTC, Sarcasm commented on irony-completion.el
> +  (and (irony-completion-candidates-available-p)
Is this code correct?
Looks like it's not only the documentation that changed, but the implementation too, the function is no longer running a task so I'm a bit surprised.

2020-10-17 08:33 UTC, merged

2020-10-17 08:34 UTC, Sarcasm commented
Although the commit is named "bad1285", I think it's a nice addition. :grinning: 
Thank you!

2020-10-17 11:48 UTC, 3246251196 commented
@Sarcasm,

I definitely think we should revert the commit. I was not happy with it.

The fact is I will never get my head around git. I have been an svn user for years and I just cannot get used to this thing. So I was making local changes on my local machine due to your review comments. Then I pushed the changes not realising they would show up here and that you would get updated. 

I think what you have done is trusted my changes too much. I have not even tested thi which I plan on doing. And I was relying on the automatic tests that normally used to run when I made a pull request. 

Are you actually happy and have you tested irony-nodebas it is with this latest commit because I fear that git is trying to tell us something with "bad" in the ID.

Thanks.

2020-10-17 12:29 UTC, Sarcasm commented
Oh, I thought you tested it locally before creating a pull request.
The initial change didn't seem working to me (removing the run-task), but you fixed that and the commit looked reasonably safe to me.
There is not much automated tests, and they usually don't test Clang, but more like helper functions.

I'm okay to revert, but what are you afraid off to be broken?
You mostly removed special cases here and there.

Before I revert, you can maybe test it a bit, and see if completion isn't broken, and that inaccessible (private?) fields aren't offered.

2020-10-17 13:22 UTC, 3246251196 commented
Hi @Sarcasm,

Let me do some testing and I'll update you later. At the latest on Sunday night. If you hear nothing then you should revert and I will perform another pull request from fresh. If it works then I will let you know. Sorry, I should have tested locally before and never realised that git push would update you. 

Let's talk soon.